execute pathogen#infect()

imap jj <Esc>
imap jk <Esc>

" Allow single character insertions from normal mode
noremap <Space> i <Esc>r

" Allow :Q and :W
com W w
com Q q

" Clear the search highlight
nnoremap <silent> <return> :noh<return>

" Navigate with jkl; instead of hjkl
noremap ; l
noremap l k
noremap k j
noremap j h

" Visual navigation by default, unless preceded by number
nnoremap <expr> k v:count ? 'j' : 'gj'
nnoremap <expr> l v:count ? 'k' : 'gk'

if has('nvim')
    " Make Esc escape Insert mode in NVIM terminal
    tnoremap <Esc> <C-\><C-n>
endif

" Alt+Arrow to move between splits
nnoremap <A-Left> <C-w>h
nnoremap <A-Down> <C-w>j
nnoremap <A-Up> <C-w>k
nnoremap <A-Right> <C-w>l

" Disable cursorline in insert mode
autocmd InsertEnter,InsertLeave * set cul!

syntax on
set backspace=indent,eol,start
set clipboard=unnamedplus
set complete-=i
set completeopt=longest,menuone
set copyindent
set cursorline
set directory=~/.vim/swap
set encoding=utf-8
set fillchars+=vert:\ 
set guicursor=
set ignorecase
set hidden
set incsearch
set infercase
set laststatus=2
set list
set listchars=tab:→\ ,trail:·
set modeline
set mouse=a
set nocompatible
set noshowmatch
set nrformats-=octal
set number
set relativenumber
set omnifunc=syntaxcomplete#Complete
set ruler
set shiftwidth=4
set smartcase
set so=3
set tabstop=4
set title
if !has('nvim') && &ttimeoutlen == -1
    set ttimeout
    set ttimeoutlen=500
endif
set timeout
set timeoutlen=500
set wildmenu

if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j " Delete comment character when joining commented lines
endif

" I use a dark theme in Konsole but a light theme elsewhere
if !empty($KONSOLE_PROFILE_NAME)
    colo gruvbox
    set background=dark
endif
let g:airline_theme='base16'
let g:airline_powerline_fonts=1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline#extensions#tabline#enabled = 1
let g:gruvbox_contrast_dark='soft'
hi Normal ctermbg=NONE
